/*

 FONDOMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : fondoSprites.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define fondoMapWidth 20
#define fondoMapHeight 18
#define fondoMapBank 0

#define fondoMap fondoMapPLN0
extern unsigned char fondoMapPLN0[];
extern unsigned char fondoMapPLN1[];

/* End of FONDOMAP.H */
