/*

 STARTSCREENMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\damia\OneDrive\Documents\Proyectos gbdk\Projects\Proyecto final gbdk\recursos\fondo.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define startscreenMapWidth 20
#define startscreenMapHeight 18
#define startscreenMapBank 0

#define startscreenMap startscreenMapPLN0
extern unsigned char startscreenMapPLN0[];
extern unsigned char startscreenMapPLN1[];

/* End of STARTSCREENMAP.H */
