/*

 FONDODATA.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 14

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define fondoDataBank 0

/* Super Gameboy palette 0 */
#define fondoDataSGBPal0c0 6076
#define fondoDataSGBPal0c1 8935
#define fondoDataSGBPal0c2 6596
#define fondoDataSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define fondoDataSGBPal1c0 6076
#define fondoDataSGBPal1c1 8935
#define fondoDataSGBPal1c2 6596
#define fondoDataSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define fondoDataSGBPal2c0 6076
#define fondoDataSGBPal2c1 8935
#define fondoDataSGBPal2c2 6596
#define fondoDataSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define fondoDataSGBPal3c0 6076
#define fondoDataSGBPal3c1 8935
#define fondoDataSGBPal3c2 6596
#define fondoDataSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define fondoDataCGBPal0c0 32767
#define fondoDataCGBPal0c1 32386
#define fondoDataCGBPal0c2 25952
#define fondoDataCGBPal0c3 0

/* Gameboy Color palette 1 */
#define fondoDataCGBPal1c0 32767
#define fondoDataCGBPal1c1 12283
#define fondoDataCGBPal1c2 25952
#define fondoDataCGBPal1c3 0

/* Gameboy Color palette 2 */
#define fondoDataCGBPal2c0 32767
#define fondoDataCGBPal2c1 8935
#define fondoDataCGBPal2c2 1473
#define fondoDataCGBPal2c3 1390

/* Gameboy Color palette 3 */
#define fondoDataCGBPal3c0 6076
#define fondoDataCGBPal3c1 8935
#define fondoDataCGBPal3c2 6596
#define fondoDataCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define fondoDataCGBPal4c0 6076
#define fondoDataCGBPal4c1 8935
#define fondoDataCGBPal4c2 6596
#define fondoDataCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define fondoDataCGBPal5c0 6076
#define fondoDataCGBPal5c1 8935
#define fondoDataCGBPal5c2 6596
#define fondoDataCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define fondoDataCGBPal6c0 6076
#define fondoDataCGBPal6c1 8935
#define fondoDataCGBPal6c2 6596
#define fondoDataCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define fondoDataCGBPal7c0 6076
#define fondoDataCGBPal7c1 8935
#define fondoDataCGBPal7c2 6596
#define fondoDataCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char fondoDataCGB[];
/* Start of tile array. */
extern unsigned char fondoData[];

/* End of FONDODATA.H */
