/*

 STARTSCREENDATA.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 10

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define startscreenDataBank 0

/* Super Gameboy palette 0 */
#define startscreenDataSGBPal0c0 6076
#define startscreenDataSGBPal0c1 8935
#define startscreenDataSGBPal0c2 6596
#define startscreenDataSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define startscreenDataSGBPal1c0 6076
#define startscreenDataSGBPal1c1 8935
#define startscreenDataSGBPal1c2 6596
#define startscreenDataSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define startscreenDataSGBPal2c0 6076
#define startscreenDataSGBPal2c1 8935
#define startscreenDataSGBPal2c2 6596
#define startscreenDataSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define startscreenDataSGBPal3c0 6076
#define startscreenDataSGBPal3c1 8935
#define startscreenDataSGBPal3c2 6596
#define startscreenDataSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define startscreenDataCGBPal0c0 32767
#define startscreenDataCGBPal0c1 32386
#define startscreenDataCGBPal0c2 25952
#define startscreenDataCGBPal0c3 0

/* Gameboy Color palette 1 */
#define startscreenDataCGBPal1c0 6076
#define startscreenDataCGBPal1c1 8935
#define startscreenDataCGBPal1c2 6596
#define startscreenDataCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define startscreenDataCGBPal2c0 6076
#define startscreenDataCGBPal2c1 8935
#define startscreenDataCGBPal2c2 6596
#define startscreenDataCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define startscreenDataCGBPal3c0 6076
#define startscreenDataCGBPal3c1 8935
#define startscreenDataCGBPal3c2 6596
#define startscreenDataCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define startscreenDataCGBPal4c0 6076
#define startscreenDataCGBPal4c1 8935
#define startscreenDataCGBPal4c2 6596
#define startscreenDataCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define startscreenDataCGBPal5c0 6076
#define startscreenDataCGBPal5c1 8935
#define startscreenDataCGBPal5c2 6596
#define startscreenDataCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define startscreenDataCGBPal6c0 6076
#define startscreenDataCGBPal6c1 8935
#define startscreenDataCGBPal6c2 6596
#define startscreenDataCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define startscreenDataCGBPal7c0 6076
#define startscreenDataCGBPal7c1 8935
#define startscreenDataCGBPal7c2 6596
#define startscreenDataCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char startscreenDataCGB[];
/* Start of tile array. */
extern unsigned char startscreenData[];

/* End of STARTSCREENDATA.H */
